# Generated by Django 6.0.7 on 2026-07-13 06:32

import comments.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/",
                validators=[comments.file_validators.validate_uploaded_file],
            ),
        ),
    ]
