# Generated by Django 6.0.7 on 2026-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
